### ISSUE TITLE
Missing metadata file when installing from repository

### ISSUE THREAD

**Issue by betsyromero** [Deltares/imod-qgis#53]
When downloading the iMOD QGIS plugin code from the Github repository, it is missing the metadata file.

**Comment by JoerivanEngelen** [comment]
Thanks for posting the issue. Via what link did you exactly download the plugin code on Github? Via releases?
Annoyingly, the zipfiles made by Github are not as QGIS expects them: QGIS expects a zipfile of the folder `imodqgis`, so one level down. To install the latest version locally, what you can do on Windows:

- Clone the repository to your local machine
- Run the ./scripts/package.bat
- Install the plugin from zip with the created zipfile

Closing now, because the metadata file is included in the Github repository and can be viewed [here](https://github.com/Deltares/imod-qgis/blob/main/imodqgis/metadata.txt). The file is included in the zipfile, but unfortunately not where QGIS expects it.

More convenient would be if the Github repository also contained installable zipfiles, so I'll create an issue for that.

**Comment by JoerivanEngelen** [comment]
Two things:
* I've created automatic packaging in the CI which uploads an installable zip as an artifact for each run, [for example](https://github.com/Deltares/imod-qgis/actions/runs/6480246311)
* I've made a Github Release, where I added an installable zip: https://github.com/Deltares/imod-qgis/releases/download/v0.4.0/imodqgis_v0.4.0.zip
